# You only can run this image if you previously built the CI image.
FROM angular-ci:latest AS build

RUN npm run build

FROM nginx:stable
COPY --from=build /usr/src/app/dist/shop-tailwind /srv
COPY --from=build /usr/src/app/nginx.conf /etc/nginx/conf.d/default.conf