env:
  LOCAL_IMAGE_NAME: "shop-tailwind_web"
  IMAGE_NAME: "angular-image"
  VERSION: "0.0.1"
  REGISTRY: "docker.pkg.github.com/gummiees/shop-tailwind"

on:
  push:
    branches:
      - main
    paths:
      - 'config/**'
      - 'site/**'
      - 'Dockerfile'
      - '.github/workflows/**'

jobs:
  build:
    name: Build the container, push it to GitHub Packages, deploys the image to a droplet on DigitalOcean
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      
    - name: Build the docker container
      run: docker-compose up -d --build

    - name: Push the image to GitHub Packages
      run: |
        # Login into GitHub container
        echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
        # Tag image
        docker tag $(echo $LOCAL_IMAGE_NAME):latest $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $VERSION)
        # Push image
        docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $VERSION)

    # - name: Push to GitHub Packages
    #   uses: docker/login-action@v1
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.repository_owner }}
    #     password: ${{ secrets.GH_TOKEN }}

    - name: Stop and destroy container and image
      run: |
        # Stop running container
        docker stop $(echo $IMAGE_NAME)
        # Remove old container
        docker rm -f $(echo $IMAGE_NAME)
        # Remove old image
        docker rmi -f $(echo $LOCAL_IMAGE_NAME)

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600
    
    - name: Deploy to Digital Ocean droplet via SSH action
      uses: appleboy/ssh-action@v0.1.3
      with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          PASSPHRASE : ${{ secrets.PASSPHRASE }}
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,COMMAND
          script: |
            # Stop running container
            docker stop $(echo $IMAGE_NAME)
            # Remove old container
            docker rm -f $(echo $IMAGE_NAME)
            # Remove old image
            docker rmi -f $(echo $LOCAL_IMAGE_NAME)
            # Run a new container from the pulled image
            docker run -d \
            --restart always \
            -p 8000:8000 \
            --name $(echo $IMAGE_NAME) \
            $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
