env:
  VERSION: "latest"
  REGISTRY_BASE_URL: "docker.pkg.github.com"
  REGISTRY: "docker.pkg.github.com/gummiees/shop-tailwind"
  DOCKERFILE_CI: "./Dockerfiles/ci/Dockerfile"
  DOCKERFILE_CD: "./Dockerfiles/cd/Dockerfile"
  CI_IMAGE_NAME: "angular-ci"
  CD_IMAGE_NAME: "angular-image"

on:
  pull_request:
    types: [opened, closed]
    branches: ["*"]
  release:
    types:
      - created

jobs:
  ci:
    name: CI workflow
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      
    - name: Build the image
      run: docker build -f $(echo $DOCKERFILE_CI) -t $(echo $CI_IMAGE_NAME) .
  cd:
    #if: github.event.pull_request.merged == true
    name: Build the container, push it to GitHub Packages, deploys the image to a droplet on DigitalOcean
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      
    - name: Build the image
      run: docker build -f $(echo $DOCKERFILE_CD) -t $(echo $CD_IMAGE_NAME) .

    - name: Push the image to GitHub Packages
      run: |
        echo Tag image
        docker tag $(echo $CD_IMAGE_NAME):latest $(echo $REGISTRY)/$(echo $CD_IMAGE_NAME):$(echo $VERSION)
        echo Login into GitHub container
        docker login $(echo $REGISTRY_BASE_URL) -u ${{ github.repository_owner }} -p ${{ secrets.GH_TOKEN }}
        echo Push image
        docker push $(echo $REGISTRY)/$(echo $CD_IMAGE_NAME):$(echo $VERSION)

    - name: Deploy to Digital Ocean droplet via SSH action
      uses: appleboy/ssh-action@v0.1.3
      with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase : ${{ secrets.PASSPHRASE }}
          envs: CD_IMAGE_NAME,REGISTRY,REGISTRY_BASE_URL,VERSION
          script: |
            echo List containers
            docker ps
            echo Stop running container
            docker stop $(echo $CD_IMAGE_NAME)
            echo Remove old container
            docker rm -f $(echo $CD_IMAGE_NAME)
            echo Remove ALL images
            docker rmi $(docker images -qf "dangling=true")
            echo List containers
            docker ps
            echo Login into GitHub Registry
            docker login $(echo $REGISTRY_BASE_URL) -u ${{ github.repository_owner }} -p ${{ secrets.GH_TOKEN }}
            echo Run a new container from the pulled image
            docker run -d --restart always -p 80:80 --name $(echo $CD_IMAGE_NAME) $(echo $REGISTRY)/$(echo $CD_IMAGE_NAME):$(echo $VERSION)