env:
  IMAGE_NAME: "angular-image"

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          repository: gummiees/shop-tailwind/$IMAGE_NAME
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
          tag_with_ref: true